adapter: sqlite3
database:  db/weather_db.sqlite
log_dir: log

development:
  adapter: sqlite3
  database:  db/weather_db.sqlite
  log_dir: log

test:
  adapter: sqlite3
  database:  db/weather_db.sqlite
  log_dir: log

production:
  adapter: postgresql
  encoding: unicode
  database: weather_db
  pool: 5
  username: weatherman
  password: